In [7]:
def a():
    return

type(a)

function

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import logging

import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline

from sklego.transformers import RandomAdder
from sklego.debug_pipeline import DebugPipeline

logging.basicConfig(
    format=('[%(funcName)s:%(lineno)d] - %(message)s'),
    level=logging.INFO
)

In [3]:
X = pd.DataFrame(np.random.randn(10, 5))
y = np.arange(10)

pipe_orig = Pipeline([
    ('random_add1', RandomAdder(noise=100)),
    ('random_add2', RandomAdder(noise=100)),
    ('random_add3', RandomAdder(noise=100)),
    ('random_add4', RandomAdder(noise=100)),
])

print(f'X before: {X}')
pipe_orig.fit(X, y=y)
X_out = pipe_orig.transform(X)
print(f'X after: \n{X_out}')

X before:           0         1         2         3         4
0 -0.940049 -0.075901  0.639286  0.132275  1.602430
1 -0.895288 -1.990152 -1.011314  0.066796 -0.472767
2 -0.894858 -1.162270  1.709011  0.236347 -2.078978
3  2.185371  1.339786  0.246841 -1.329772 -1.062015
4  1.202885 -0.579886 -0.230075  0.791553  0.617815
5  0.232327 -0.563682  0.435348 -1.613973  1.761367
6  0.323429  0.769809  0.478552  0.740840  0.116635
7  0.718012  0.601780 -0.837163 -0.725796 -1.190399
8 -0.461161 -1.125952  0.315964 -0.067506 -0.647913
9  0.255035  1.143398  0.206254 -0.199667 -0.323808
X after: 
[[ -87.10882477 -133.36539532  101.71450612  207.61903647   37.90230601]
 [ 212.0240614   250.6199743   131.66940743 -299.06546697   44.57263835]
 [-115.91596354  -47.67033042  395.27175579   -6.99635723  -26.72416042]
 [-208.08483167  324.28995645 -287.30349345 -101.03733801  487.84684609]
 [ -67.73895898  -42.39044488 -128.11222684 -220.99077831  107.26380853]
 [-149.575734    -46.71882313  -64.55530049

In [4]:
X = pd.DataFrame(np.random.randn(10, 5))
y = np.arange(10)

pipe = DebugPipeline([
#     ('pipeline_massive', pipe_orig),
    ('random_add1', RandomAdder(noise=1)),
    ('random_add2', RandomAdder(noise=10)),
    ('random_add3', RandomAdder(noise=100)),
    ('random_add4', RandomAdder(noise=1000)),
])

# print(f'X before: {X}')
pipe.fit(X, y=y)
X_out = pipe.transform(X)
# print(f'X after: \n{X_out}')

[wrapper:24] - [RandomAdder(noise=1, random_state=None)] shape=(10, 5) time=0:00:00.001068
[wrapper:24] - [RandomAdder(noise=10, random_state=None)] shape=(10, 5) time=0:00:00.000185
[wrapper:24] - [RandomAdder(noise=100, random_state=None)] shape=(10, 5) time=0:00:00.000173


In [5]:
f = pipe.memory.cache(lambda df: (np.array([0, 1, 2]), 'foo'))
f(X)

[wrapper:24] - [foo] shape=(3,) time=0:00:00.000014


(array([0, 1, 2]), 'foo')